### ISSUE TITLE
Using vfsm_util with windows 

### ISSUE THREAD

**Issue by SBCV** [nrhine1/vsfm_util#1]
When running "test_vsfm_socket_util.py" under windows and python 2.7.10 I get the following error message:
"pickle.PicklingError: Can't pickle <built-in method recvfrom_into of _socket.socket object at 0x0000000002015B70>: it's not found as **main**.recvfrom_into"

This can be fixed by adding 

```
from pathos.helpers import freeze_support
    if __name__ == '__main__':
    freeze_support()
```

before

```
example_dir = 'examples/kermit'
os.chdir(example_dir)
```

Excerpt from another github [thread](https://github.com/uqfoundation/pathos/issues/67):

> Second item to note is that Windows works differently than non-windows systems. Much of the time, for the ProcessPool, Windows requires from pathos.helpers import freeze_support, then freeze_support(). It's unnecessary for non-windows systems. Windows often requires freeze_support to be provided in __main__.

I guess a note for windows user would be useful ;)

p.s. Of course, this asumes that [pathos](https://github.com/uqfoundation/pathos) is installed.

**Comment by nrhinehart** [comment]
Thanks for reporting this, if you want to make a PR that includes a windows check (i.e. `if os.name == 'nt'`) to prevent the `pathos` requirement for non-Windows users, I'll merge it

**Comment by punisher220** [comment]
Excuse me, @nrhine1 .I am sorry to bother you. In which python version can the code work? Python3 or Python2.x?

**Comment by punisher220** [comment]
Well, sorry for asking the question. I found out that Python2.7.18 can work.

**Comment by punisher220** [comment]
Hi,
I am testing the python socket for VSFM in Windows10 with the help of @SBCV by adding 

`from pathos.helpers import freeze_support
    if __name__ == '__main__':
    freeze_support()`

with installing pathos0.2.6 but an error occurred:

`AttributeError: 'module' object has no attribute 'SIGQUIT'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\LIFT_trial\Python2_7\Bin\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\LIFT_trial\Python2_7\Bin\lib\multiprocessing\forking.py", line 510, in prepare
    '__parents_main__', file, path_name, etc
  File "D:\LIFT_trial\VSFM_read\test_vsfm_socket_util.py", line 11, in <module>
    os.chdir(example_dir)
WindowsError: [Error 3] : 'examples/kermit'`

I have set the **path_to_vsfm_bin** path with my own Visual SFM folder path including **VisualSFM.exe**
How to solve the problem?

**Comment by SBCV** [comment]
Hi, 
I'm afraid I can't help you out here, since I stopped working with VisualSfM a few years ago.
I don't know if you have any restrictions, but instead of fixing this problem, I would rather suggest to replace your VisualSfM backbone with another library such as [Colmap](https://github.com/colmap/colmap), [OpenMVG ](https://github.com/openMVG/openMVG) or [Meshroom ](https://alicevision.org/). 
These tools provide much better results than VisualSfM (checkout [this ](https://www.tanksandtemples.org/leaderboard/) link) and are actively developed. I know that this is potentially an overkill for your application case, but I just wanted to make sure, that you don't waste your time with a tool that no longer represents the state of the art. 
And since VisualSfM is not fully open sourced, you have also additional restrictions when it comes to changing the code base ... 
Cheers

**Comment by punisher220** [comment]
@SBCV Thanks for your reply. Yes, there are 3D reconstruction tools better than VSFM. 

But recently I was trying to re-perform the training data pre-processing stage for 
https://github.com/cvlab-epfl/tf-lift
which requires to convert the feature point descriptors and match information(the .sift files and the .mat files) and nvm model information(the .nvm file) from VSFM(The author used the VSFM)  into h5py files to train CNN network for image feature point extraction like SIFT.  This is the reason for me to dig into the VSFM.

Unfortunately I got stuck in the converting. The code of this part is not open-sourced which made me upset. The latest PR for it has solved part of the converting but due to COVID the update of the PR got stuck. 

Now I need to read the data from .sift files to get the 128-dimension descriptors information and write it into h5py file to finish the converting part. 
Until present I still have not made it. I am still searching for the code in Python or C++ to load the .sift files. Then I came here.
Thanks for your reply.
